on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 기본 체크아웃
      - name: Checkout
        uses: actions/checkout@v3

      # Gradlew 실행 허용
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

      # JDK 21 세팅 (SpringBoot 3.2.x와 Java 21 호환)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # 환경 변수 설정 (GitHub Secrets를 이용해 env.properties 파일 생성)
      - name: Create env.properties from Secrets
        run: |
          cd ./src/main/resources
          touch ./env.properties
          echo "KEY=${{ secrets.ENV }}" > ./env.properties
        shell: bash

      # Gradle build (Test 제외)
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean build -x test

      # Gradle build (Test 제외)
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: clean build -x test

      # Docker build
      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker build -t ssaffeine_docker_hub .
          docker tag ssaffeine_docker_hub wnsgh712/ssaffeine_docker_hub:${GITHUB_SHA::7}
          docker push wnsgh712/ssaffeine_docker_hub:${GITHUB_SHA::7}

      # Deploy
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 35.216.108.230
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
            sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${GITHUB_SHA::7}
            sudo docker tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${GITHUB_SHA::7} 이미지이름
            sudo docker-compose up -d
